const types = {
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    LOG_OUT: "LOG_OUT",
    LOGIN_USER_CREATED: "LOGIN_USER_CREATED",

    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    USERS_DATA_FETCH_BY_ID_SUCCESS: "USERS_DATA_FETCH_BY_ID_SUCCESS",
    USERS_FETCH_FETCH_BY_ID_SUCCESS: "USERS_UPDATE_BY_ID_SUCCESS",
    USERS_DATA_UPDATE: "USER_DATA_UPDATE"
}